services:
  clean-ui:
    image: ghcr.io/j4ys0n/clean-ui:sha-6cd75bf
    container_name: clean-ui
    environment:
      - MODEL_NAME=unsloth/Llama-3.2-11B-Vision-Instruct
      - MAX_OUTPUT_TOKENS=32768
      - SERVER_PORT=7860
    ports:
      - 7860:7860
    volumes:
      - ./cache:/root/.cache
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]